NG1.4

diff --git a/bihourly b/bihourly
--- a/bihourly
+++ b/bihourly
@@ -1,30 +1,65 @@
 #!/bin/sh
-# @(#) $Header: bihourly,v 1.1 96/11/07 17:39:23 leres Exp $ (LBL)
+# @(#) $Id: bihourly.sh,v 1.2 2006/07/28 18:19:32 leres Exp $ (LBL)
 #
 #  bihourly arpwatch job
 #
-PATH=$PATH:/usr/local/sbin
+PATH=${PATH}:/usr/local/sbin
 export PATH
 #
 cd /usr/operator/arpwatch
 #
-list=`cat list`
-cname=`cat cname`
-errs=/tmp/bihourly.$$
-errs=`tempfile -p arpbh -s .tmp`
-#
+list="`cat list`"
+cname="`cat cname`"
+temp1=/tmp/bihourly.1.$$
+temp2=/tmp/bihourly.2.$$
+d=/tmp/errs
+
+# imperfect hack
+l=/tmp/bihourly.lock
+if [ -f ${l} ]; then
+	echo "skipping arpwatch bihourly job, lock file exists"
+	exit
+fi
+
+trap 'rm -f ${l}; exit 1' 1 2 3 15
+touch ${l}
+
 alist=""
-for r in $list; do \
-	./arpfetch $r $cname > $r 2> $errs
-	if test -s $errs; then
-		echo "arpfetch $r failed:"
-		sed -e 's/^/    /' $errs
+for r in ${list}; do \
+	./arpfetch ${r} ${cname} > ${r} 2> ${temp1}
+	if [ -s ${temp1} ]; then
+		echo "arpfetch ${r} errors:"
+		xr=${d}/${r}.$$
+		echo "(file ${r} saved in ${xr})"
+		mkdir -p ${d}
+		cp ${r} ${xr}
+		sed -e 's/^/    /' ${temp1}
 		continue
 	fi
-	alist="$alist $r"
+	alist="${alist} ${r}"
 done
-#
-rm -f $errs
-arpsnmp $alist
-#
+
+arpsnmp -d ${alist} > ${temp1} 2>&1
+
+sed -e '/arpsnmp: suppressed DECnet flip flop/d' ${temp1} > ${temp2}
+if [ -s ${temp2} ]; then
+	mail -s "`hostname` arpwatch report" \
+	    arpwatch-reports@noname.lbl.gov < ${temp2}
+fi
+rm -f ${temp1} ${temp2}
+
+d=/www/NETINFO/arpwatch
+
+f=arp.dat
+cp ${f} ${d}
+
+f=ethercodes.dat
+diff ethercodes.dat ${d} >>/dev/null 2>&1
+if [ $? -ne 0 ]; then
+	echo Updating ${d}/${f}
+	cp ${f} ${d}
+fi
+
+rm ${l}
+
 exit 0
